[modules]
autoload=yes
preload=res_pjproject.so
preload=res_pjsip.so
preload=chan_pjsip.so
preload=res_pjsip_authenticator_digest.so
preload=res_pjsip_endpoint_identifier_ip.so
preload=res_pjsip_endpoint_identifier_user.so
preload=res_pjsip_registrar.so
preload=res_rtp_asterisk.so
preload=res_srtp.so

noload => chan_sip.so
noload => res_sip.so

